name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in infracloud.io posts
        uses: gautamkrishnar/blog-post-workflow@v1
        id: blog-post-workflow
        with:
          max_post_count: 3
          feed_list: "https://deploy-preview-853--infracloud.netlify.app/feed.xml"
          custom_tags: "author/author/name,published/published"
          template: |
            <table>
              <tr><td><a href="$url"><img width="140px" src="$image" /></a></td></tr>
              <tr><td><strong>$category</strong></td></tr>
              <tr><td><a href="$url" style="text-decoration:none;color:#000;"><h3>$title</h3></a></td></tr>
              <tr><td>by <em>$author</em> on $published<br/>$reading_time min read</td></tr>
            </table>
