name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in infracloud.io posts
        uses: gautamkrishnar/blog-post-workflow@v1
        id: blog-post-workflow
        with:
          max_post_count: 2
          feed_list: "https://deploy-preview-853--infracloud.netlify.app/feed.xml"
          custom_tags: "title/title/,link/link/@href,author/author/name,published/published,thumbnail/media:thumbnail/@url"
          date_format: "mmm d, yyyy"
          template: |
            <table>
              <tr>
                <td>
                  <a href="$link">
                    <img width="140px" src="$thumbnail">
                  </a>
                </td>
                <td>
                  <a href="$link">$title</a>
                  <br/>
                  by $author on $published
                </td>
              </tr>
            </table>
            $newline